INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Islam', 'Dudaev', '(age 29)', 'Amateur wrestling', 'Freestyle', 'Chechen', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Djamel', 'Sedjati', '(age 25)', 'Athletics', '600 meters 800 meters', 'Algerian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Walid', 'Bidani', '(age 29)', 'Weightlifting', '+105 kg', 'Algerian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Abdelkarim', 'Fergat', '(age 30)', 'Amateur wrestling', 'Greco-Roman', 'Algerian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Abdelkrim', 'Ouakali', '(age 31)', 'Wrestling', 'Greco-Roman', 'Algerian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Santiago', 'Lorenzo', '(age 46)', 'Athletics', 'Notes', 'Argentina', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Vazgen', 'Tevanyan', '(age 24)', 'Amateur wrestling', 'Freestyle', 'Armenia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Slavik', 'Galstyan', '(age 27)', 'Wrestling', 'Greco-Roman', 'Armenian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Artur', 'Aleksanyan', '(age 32)', 'Wrestling', 'Greco-Roman', 'Armenian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kyle', 'Swan', '(age 25)', 'Athletics', 'Racewalking', 'Australian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Abbey', 'Caldwell', '(age 22)', 'Track and Field', 'Middle distance', 'Australian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lauren', 'Ryan', '(age 26)', 'Athletics', 'Long distance running', 'Australian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Matthew', 'Denny', '(age 27)', 'Athletics', 'Notes', 'Australian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nicola', 'Olyslagers', '(age 27)', 'Athletics', 'High jump', 'Australian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Eleanor', 'Patterson', '(age 28)', 'Track and field', 'High jump', 'Australian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Alyce', 'Wood', '(age 31)', 'Canoe sprint', 'K1, K2', 'Australian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nicholas', 'Sloman', '(age 26)', 'Open water swimming', '1st', 'Australian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Susanne', 'Gogl-Walli', '(age 28)', 'Athletics', '400 metres', 'Austrian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Hanna', 'Skydan', '(age 32)', 'Track and field', 'Notes', 'Ukraine (until 2014) Azerbaijan (since January 2015)', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aliabbas', 'Rzazade', '(age 26)', 'Amateur wrestling', 'Freestyle', 'Azerbaijan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Turan', 'Bayramov', '(age 23)', 'Amateur wrestling', 'Location', 'Azerbaijan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Osman', 'Nurmagomedov', '(age 26)', 'Amateur wrestling', 'Notes', 'Azerbaijan Russia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Hasrat', 'Jafarov', '(age 21)', 'Amateur wrestling', 'Greco-Roman', 'Azerbaijan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Steven', 'Gardiner', '(age 28)', 'Track and field', 'Notes', 'Bahamian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Anthonique', 'Strachan', '(age 30)', 'Running', 'Notes', 'Bahamas', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Desi', 'Mokonin', '(age 26)', 'Long-distance running', '10,000 metres', 'Bahraini', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rose', 'Chelimo', '(age 34)', 'Athletics', 'Notes', 'Bahraini', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lesman', 'Paredes', '(age 28)', 'Weightlifting', '96 kg', 'Bahraini', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Gor', 'Minasyan', '(age 29)', 'Weightlifting', '+109 kg', 'Armenia Bahrain', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Akhmed', 'Tazhudinov', '(age 21)', 'Amateur wrestling', 'Location', 'Russian Bahraini', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('John', 'Heymans', '(age 26)', 'Track and field', 'Time', 'Belgian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Isaac', 'Kimeli', '(age 30)', 'Athletics', 'Result', 'Kenyan-Belgian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Michael', 'Obasuyi', '(age 24)', 'Athletics', 'Notes', 'Belgium', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Letsile', 'Tebogo', '(age 20)', 'Athletics', 'Time', 'Botswana', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Bayapo', 'Ndori', '(age 24)', 'Athletics', '400 metres', 'Botswana', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Felipe', 'Bardi', '(age 25)', 'Athletics', 'Result', 'Brazilian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Caio', 'Bonfim', '(age 33)', 'Athletics', 'Notes', 'Brazilian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Caio', 'Bonfim', '(age 33)', 'Athletics', 'Notes', 'Brazilian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Darlan', 'Romani', '(age 33)', 'Track and field', 'Result', 'Brazilian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pepe', 'Gonçalves', '(age 31)', 'Canoe slalom', 'K1, C1, Extreme K1', 'Brazilian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ana', 'Sátila', '(age 28)', 'Canoe slalom', 'C1, K1, Kayak cross', 'Brazilian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Isaquias', 'Queiroz', '(age 30)', 'Sprint canoe', '1st', 'Brazilian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Isaac', 'Souza', '(age 24)', 'Diving', '10 metre springboard', 'Brazil', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Gabrielle', 'Roncatto', '(age 25)', 'Swimming', 'Time', 'Brazil', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Stanimira', 'Petrova', '(age 33)', 'Boxing', '1st', 'Bulgarian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kimia', 'Alizadeh', '(age 25)', 'Taekwondo', '1st', 'Iranian Bulgarian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ben', 'Flanagan', '(age 29)', 'Track and field', 'Time', 'Canadian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Malindi', 'Elmore', '(age 44)', 'Womens athletics', 'Notes', 'Canadian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Josipa', 'Kafadar', '(age 23)', 'Taekwondo', '–49 kg', 'Canadian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Skylar', 'Park', '(age 24)', 'Taekwondo', '–57 kg', 'Canadian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Linda', 'Morais', '(age 30)', 'Wrestling', 'Freestyle', 'Canadian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Yasmani', 'Acosta', '(age 35)', 'Amateur wrestling', 'Greco-Roman', 'Chilean Cuban', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lin', 'Yuwei', '(age 25)', 'Athletics', '100 metres hurdles', 'China', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Gong', 'Lijiao', '(age 35)', 'Athletics', 'Shot put', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Feng', 'Bin', '(age 30)', 'Track and field', 'Notes', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sheng', 'Lihao', '(age 19)', 'Shooting', '10 metre air rifle', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pan', 'Zhanle', '(age 19)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pan', 'Zhanle', '(age 19)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pan', 'Zhanle', '(age 19)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ji', 'Xinjie', '(age 26)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pan', 'Zhanle', '(age 19)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Xu', 'Jiayu', '(age 28)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Qin', 'Haiyang', '(age 25)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Qin', 'Haiyang', '(age 25)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Dong', 'Zhihao', '(age 19)', 'Swimming', 'Time', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Yang', 'Junxuan', '(age 22)', 'Swimming', '1st', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Yang', 'Junxuan', '(age 22)', 'Swimming', '1st', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Li', 'Bingjie', '(age 22)', 'Swimming', 'Time', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Li', 'Bingjie', '(age 22)', 'Swimming', 'Time', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Li', 'Bingjie', '(age 22)', 'Swimming', 'Time', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Li', 'Bingjie', '(age 22)', 'Swimming', 'Time', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Peng', 'Xuwei', '(age 21)', 'Swimming', '1st', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tang', 'Qianting', '(age 20)', 'Swimming', 'Time', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Li', 'Fabin', '(age 31)', 'Weightlifting', '–61 kg', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Liu', 'Huanhua', '(age 22)', 'Weightlifting', '–102 kg', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Hou', 'Zhihui', '(age 27)', 'Weightlifting', '–49 kg', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Li', 'Wenwen', '(age 24)', 'Weightlifting', '+87 kg', 'Chinese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zou', 'Wanhao', '(age 26)', 'Amateur wrestling', 'Freestyle', 'China', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Cao', 'Liguo', '(age 25)', 'Amateur wrestling', 'Greco-Roman', 'China', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Meng', 'Lingzhe', '(age 26)', 'Amateur wrestling', 'Greco-Roman', 'China', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ronal', 'Longa', '(age 19)', 'Athletics', 'Result', 'Colombian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Éider', 'Arévalo', '(age 31)', 'Athletics', 'Notes', 'Colombian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Angie', 'Orjuela', '(age 35)', 'Track and field', 'Marathon', 'Colombian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sandra', 'Arenas', '(age 30)', 'Athletics', 'Result', 'Colombian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ingrit', 'Valencia', '(age 35)', 'Boxing', '1st', 'Colombian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Daniel', 'Restrepo', '(age 24)', 'Diving', '1st', 'Colombian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sandra', 'Perković', '(age 33)', 'Athletics', 'Discus throw', 'Croatian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Roxana', 'Gómez', '(age 25)', 'Track and field', 'Notes', 'Cuban', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Leyanis', 'Pérez', '(age 22)', 'Track and Field', 'triple jump', 'Cuban', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Denia', 'Caballero', '(age 34)', 'Athletics', 'Notes', 'Cuban', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Jakub', 'Vadlejch', '(age 33)', 'Track and field', 'Javelin throw', 'Czech', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lukáš', 'Rohan', '(age 28)', 'Canoe slalom', 'C1, C2', 'Czech', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Gabriela', 'Satková', '(age 22)', 'Canoe slalom', 'C1, K1', 'Czech', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Daniel', 'Havel', '(age 32)', 'Sprint kayak', '1st', 'Czech', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Anežka', 'Paloudová', '(age 25)', 'Canoeing', '1st', 'Czech', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sverri', 'Nielsen', '(age 30)', 'Rowing', 'Single sculls', 'Faroese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rikke', 'Ibsen', '(age 33)', 'Shooting', 'Air rifle', 'Danish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Beatriz', 'Pirón', '(age 29)', 'Weightlifting', '–48 kg', 'Dominican', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Crismery', 'Santana', '(age 29)', 'Weightlifting', '–87 kg', 'Dominican', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('David', 'Hurtado', '(age 25)', 'Mens athletics', 'Racewalking', 'Ecuadorian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Brian', 'Pintado', '(age 28)', 'Athletics', 'Racewalking', 'Ecuadorian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Jordy', 'Jiménez', '(age 30)', 'Mens athletics', 'Racewalking', 'Ecuadorian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('David', 'Farinango', '(age 23)', 'Swimming', 'Marathon swimming', 'Ecuador', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Angie', 'Palacios', '(age 23)', 'Weightlifting', '64 kg', 'Ecuadorian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Neisi', 'Dajomes', '(age 26)', 'Weightlifting', '–76 kg', 'Ecuadorian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Malak', 'Hamza', '(age 22)', 'Trampoline gymnastics', 'Womens trampoline', 'Egypt', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Abdelrahman', 'El-Sayed', '(age 35)', 'Weightlifting', '105 kg', 'Egypt', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Eneli', 'Jefimova', '(age 17)', 'Swimming', '1st', 'Estonian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Berihu', 'Aregawi', '(age 23)', 'Athletics', 'Result', 'Ethiopian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kenenisa', 'Bekele', '(age 41)', 'Track, Long-distance running', 'Notes', 'Ethiopian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tamirat', 'Tola', '(age 32)', 'Athletics', 'Result', 'Ethiopian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sembo', 'Almayew', '(age 19)', 'Athletics', '3000 metres steeplechase', 'Ethiopian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lomi', 'Muleta', '(age 22)', 'Athletics', 'Steeplechase', 'Ethiopian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zerfe', 'Wondemagegn', '(age 21)', 'Athletics', 'Steeplechase', 'Ethiopian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Gotytom', 'Gebreslase', '(age 29)', 'Athletics', 'Time', 'Ethiopian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Amane', 'Beriso', '(age 32)', 'Athletics', 'Long-distance running', 'Ethiopian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Viivi', 'Lehikoinen', '(age 24)', 'Athletics', 'Time', 'Finnish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Silja', 'Kosonen', '(age 21)', 'Athletics', 'Notes', 'Finland', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nicolas', 'Gestin', '(age 24)', 'Canoe slalom', 'Result', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Titouan', 'Castryck', '(age 19)', 'Canoe slalom', 'K1, Kayak cross', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Marjorie', 'Delassus', '(age 26)', 'Canoe slalom', 'C1, K1', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Camille', 'Prigent', '(age 26)', 'Canoe slalom', 'K1', 'French', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Titouan', 'Castryck', '(age 19)', 'Canoe slalom', 'K1, Kayak cross', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Camille', 'Prigent', '(age 26)', 'Canoe slalom', 'K1', 'French', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Adrien', 'Bart', '(age 32)', 'Sprint canoe', 'C-1 1000 m', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Manon', 'Hostens', '(age 29)', 'Canoeing', '1st', 'French', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Clément', 'Bessaguet', '(age 32)', 'Shooting', 'Air pistol', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Jean', 'Quiquampoix', '(age 28)', 'Shooting', 'Air pistol', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Logan', 'Fontaine', '(age 25)', 'Open water swimming', '5 km', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Cyrian', 'Ravet', '(age 21)', 'Taekwondo', '58 kg', 'French', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Magda', 'Wiet-Hénin', '(age 28)', 'Taekwondo', '62 kg (lightweight)', 'French', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Marie', 'Fegue', '(age 32)', 'Weightlifting', '69 kg', 'Cameroonian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sandro', 'Bazadze', '(age 30)', 'Fencing', 'Position', 'Georgian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Shota', 'Mishvelidze', '(age 29)', 'Weightlifting', '61 kg', 'Georgian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Irakli', 'Chkheidze', '(age 25)', 'Weightlifting', '102 kg', 'Georgia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lasha', 'Talakhadze', '(age 30)', 'Weightlifting', '+109 kg', 'Georgia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ramaz', 'Zoidze', '(age 28)', 'Amateur wrestling', 'Greco-Roman', 'Georgia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Robert', 'Kobliashvili', '(age 30)', 'Wrestling', 'Greco-Roman', 'Georgian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Richard', 'Ringer', '(age 35)', 'Athletics', 'Notes', 'German', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sideris', 'Tasiadis', '(age 34)', 'Canoe slalom', 'C1', 'German', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Noah', 'Hegge', '(age 25)', 'Canoe slalom', 'Result', 'German', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Elena', 'Lilik', '(age 25)', 'Canoe slalom', 'C1, K1, Kayak cross', 'German', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ricarda', 'Funk', '(age 32)', 'Canoe slalom', '2014', 'German', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Jello', 'Krahmer', '(age 28)', 'Wrestling', 'Greco-Roman', 'German', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Megan', 'Keith', '(age 22)', 'Athletics', '5000m', 'Scottish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rose', 'Harvey', '(age 31)', 'Athletics', 'Marathon', 'Great Britain', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Charlotte', 'Purdue', '(age 32)', 'Athletics/Cross Country Running', 'Notes', 'English', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Adam', 'Burgess', '(age 31)', 'Canoe slalom', 'C1, C2', 'British', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mallory', 'Franklin', '(age 29)', 'Canoe slalom', 'C1, K1, Kayak cross', 'English', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kimberley', 'Woods', '(age 28)', 'Canoe slalom', 'C1, K1, Kayak cross', 'English', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mallory', 'Franklin', '(age 29)', 'Canoe slalom', 'C1, K1, Kayak cross', 'English', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kimberley', 'Woods', '(age 28)', 'Canoe slalom', 'C1, K1, Kayak cross', 'English', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Jonathon', 'Marshall', '(age 19)', 'Swimming', 'Backstroke', 'British (English)', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Hector', 'Pardoe', '(age 23)', 'Swimming', 'Marathon swimming', 'British', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tobias', 'Robinson', '(age 27)', 'Swimming', 'freestyle', 'British (English)', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Honey', 'Osrin', '(age 21)', 'Swimming', 'Backstroke', 'British (English)', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Keanna', 'Macinnes', '(age 22)', 'Swimming', 'Butterfly', 'British (Scottish)', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Keanna', 'Macinnes', '(age 22)', 'Swimming', 'Butterfly', 'British (Scottish)', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Medi', 'Harris', '(age 21)', 'Swimming', 'Backstroke', 'British Welsh', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Angharad', 'Evans', '(age 21)', 'Swimming', 'Breaststroke', 'British (English)', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Keanna', 'Macinnes', '(age 22)', 'Swimming', 'Butterfly', 'British (Scottish)', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Leah', 'Crisp', '(age 22)', 'Swimming', '800m/1500m freestyle', 'British (English)', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Caden', 'Cunningham', '(age 21)', 'Taekwondo', '+ 87 kg Height. = 1.84m', 'British', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Anna', 'Korakaki', '(age 28)', 'Shooting', 'Air pistol', 'Greek', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kristian', 'Gkolomeev', '(age 30)', 'Swimming', '1st', 'Greek Bulgarian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Evangelos', 'Makrygiannis', '(age 23)', 'Swimming', 'backstroke', 'Greece', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kristian', 'Gkolomeev', '(age 30)', 'Swimming', '1st', 'Greek Bulgarian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Dauren', 'Kurugliev', '(age 31)', 'Wrestling', 'Freestyle', 'Lezgin', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kirani', 'James', '(age 31)', 'Track and field', 'Notes', 'Grenadian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Anderson', 'Peters', '(age 26)', 'Track and field', 'Notes', 'Grenadian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rckaela', 'Aquino', '(age 24)', 'Wrestling', 'Freestyle', 'Guamanian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Vivian', 'Kong', '(age 30)', 'Fencing', 'Position', 'Chinese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Bence', 'Halász', '(age 26)', 'Athletics', 'Notes', 'Hungarian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Parul', 'Chaudhary', '(age 29)', 'Track and field', 'Long-distance running', 'Indian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kishore', 'Jena', '(age 28)', 'Athletics', 'Javelin throw', 'Indian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nikhat', 'Zareen', '(age 27)', 'Boxing', '1st', 'Indian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Arjun', 'Babuta', '(age 25)', 'Shooting', '10 meter air rifle', 'Indian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sarabjot', 'Singh', '(age 22)', 'Shooting', '10 meter air pistol', 'Indian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Anjum', 'Moudgil', '(age 30)', 'Shooting', 'Air rifle', 'Indian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aman', 'Sehrawat', '(age 20)', 'Wrestling', 'Location', 'India', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Vinesh', 'Phogat', '(age 29)', 'Freestyle wrestling', 'Rank', 'Indian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Antim', 'Panghal', '(age 19)', 'Freestyle wrestling', 'Location', 'Indian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Anshu', 'Malik', '(age 22)', 'Freestyle wrestling', 'Location', 'Indian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Maksim', 'Khramtsov', '(age 26)', 'Taekwondo', '–80 kg', 'Russian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Vladislav', 'Larin', '(age 28)', 'Taekwondo', 'Heavyweight (+87 kg)', 'Russian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Polina', 'Khan', '(age 24)', 'Taekwondo', '–73 kg', 'Russian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Petr', 'Asayonak', '(age 31)', 'Weightlifting', 'Weight', 'Belarusian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Yauheni', 'Tsikhantsou', '(age 25)', 'Weightlifting', '–102 kg', 'Balrussian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Eduard', 'Ziaziulin', '(age 25)', 'Weightlifting', '+109 kg', 'Belarusian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zaur', 'Uguev', '(age 29)', 'Wrestling', 'Location', 'Russia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aryan', 'Tsiutryn', '(age 29)', 'Amateur wrestling', 'Freestyle', 'Russia Belarus', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Shamil', 'Mamedov', '(age 23)', 'Wrestling', 'Freestyle', 'Russia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mahamedkhabib', 'Kadzimahamedau', '(age 29)', 'Wrestling', 'Freestyle', 'Belarus', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Alikhan', 'Zhabrailov', '(age 29)', 'Amateur wrestling', 'Location', 'Russia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aliaksandr', 'Hushtyn', '(age 30)', 'Amateur wrestling', 'Freestyle', 'Belarus', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nadezhda', 'Sokolova', '(age 27)', 'Wrestling', 'Freestyle', 'Russia', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Vanesa', 'Kaladzinskaya', '(age 31)', 'Wrestling', 'Freestyle', 'Belarus', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Olga', 'Khoroshavtseva', '(age 29)', 'Amateur wrestling', 'Freestyle', 'Russian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sergey', 'Kutuzov', '(age 25)', 'Amateur wrestling', 'Greco-Roman', 'Russia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mirmostafa', 'Javadi', '(age 23)', 'Weightlifting', '89 kg', 'Iranian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ali', 'Davoudi', '(age 25)', 'Weightlifting', '+109 kg', 'Iran', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rahman', 'Amouzad', '(age 21)', 'Wrestling', 'Location', 'Iran', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Andrew', 'Coscoran', '(age 27)', 'Athletics', '1500 metres', 'Irish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sharlene', 'Mawdsley', '(age 25)', 'Athletics', '400 metres', 'Irish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Shelly', 'Bobritsky', '(age 22)', 'Artistic swimming', 'Points', 'Israeli', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Matan', 'Roditi', '(age 25)', 'Swimming', '10 kilometre marathon', 'Israeli', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Alice', 'Sotero', '(age 32)', 'Modern pentathlon', 'Time', 'Italian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Matteo', 'Zurloni', '(age 22)', 'Competition speed climbing', 'Speed', 'Italian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lorenzo', 'Zazzeri', '(age 29)', 'Swimming', '1st', 'Italian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Manuel', 'Frigo', '(age 27)', 'Swimming', '1st', 'Italian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Arianna', 'Bridi', '(age 28)', 'Swimming', 'Time', 'Italian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Antonino', 'Pizzolato', '(age 27)', 'Weightlifting', '-89 kg', 'Italian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lucrezia', 'Magistris', '(age 25)', 'Weightlifting', '-59 kg', 'Italian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Jessika', 'Gbai', '(age 25)', 'Athletics', 'Sprint', 'Ivory Coast', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Maboundou', 'Koné', '(age 27)', 'Athletics', 'Sprint', 'Ivory Coast', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Fuga', 'Sato', '(age 27)', 'Athletics', '400 metres', 'Japanese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kazuki', 'Kurokawa', '(age 22)', 'Athletics', 'Hurdles', 'Japanese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kento', 'Yoshida', '(age 31)', 'Fencing', 'Position', 'Japan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Taishin', 'Minamide', '(age 28)', 'Swimming', 'Marathon swimming', 'Japan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rei', 'Higuchi', '(age 28)', 'Wrestling', 'Freestyle', 'Japan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Daichi', 'Takatani', '(age 29)', 'Amateur wrestling', 'Freestyle', 'Japan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Akari', 'Fujinami', '(age 20)', 'Wrestling', 'Freestyle', 'Japan', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tsugumi', 'Sakurai', '(age 22)', 'Amateur wrestling', 'Freestyle', 'Japan', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Julyana', 'Al-Sadeq', '(age 29)', 'Taekwondo', '–67 kg', 'Jordanian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zhanna', 'Mamazhanova', '(age 30)', 'Womens athletics', 'Notes', 'Kazakh', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Norah', 'Jeruto', '(age 28)', 'Athletics', 'Time', 'Kenyan Kazakhstani', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Azamat', 'Dauletbekov', '(age 30)', 'Amateur wrestling', 'Freestyle', 'Kazakhstan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aidos', 'Sultangali', '(age 28)', 'Amateur wrestling', 'Greco-Roman', 'Kazakhstan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nursultan', 'Tursynov', '(age 33)', 'Amateur wrestling', 'Greco-Roman', 'Kazakhstan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Benson', 'Kipruto', '(age 33)', 'Athletics', 'Marathon', 'Kenyan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mary', 'Moraa', '(age 23)', 'Athletics', 'Time', 'Kenyan', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Peres', 'Jepchirchir', '(age 30)', 'Athletics', 'Result', 'Kenyan', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ernazar', 'Akmataliev', '(age 25)', 'Freestyle wrestling', 'Opposition', 'Kyrgyzstani', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aiaal', 'Lazarev', '(age 38)', 'Amateur wrestling', 'Freestyle', 'Russia Kyrgyzstan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Meerim', 'Zhumanazarova', '(age 24)', 'Wrestling', 'Freestyle', 'Kyrgyzstan', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zholaman', 'Sharshenbekov', '(age 24)', 'Wrestling', 'Greco-Roman', 'Kyrgyzstan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Akzhol', 'Makhmudov', '(age 25)', 'Wrestling', '1st', 'Kyrgyzstan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Uzur', 'Dzhuzupbekov', '(age 28)', 'Amateur wrestling', 'Greco-Roman', 'Kyrgyzstani', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kristaps', 'Neretnieks', '(age 34)', 'Equestrian', 'Show jumping', 'Latvian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ritvars', 'Suharevs', '(age 25)', 'Weightlifting', '–81 kg', 'Latvia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mykolas', 'Alekna', '(age 21)', 'Athletics', 'Notes', 'Lithuanian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ieva', 'Gumbs', '(age 29)', 'Athletics', 'Discus throw', 'Lithuanian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Danas', 'Rapšys', '(age 29)', 'Swimming', '1st', 'Lithuanian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Danas', 'Rapšys', '(age 29)', 'Swimming', '1st', 'Lithuanian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Bob', 'Bertemes', '(age 30)', 'Athletics', 'Notes', 'Luxembourgish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rosina', 'Randafiarison', '(age 24)', 'Weightlifting', 'Rank', 'Malagasy', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aniq', 'Kasdan', '(age 21)', 'Weightlifting', '55 kg', 'Malaysian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Jordan', 'Gusman', '(age 30)', 'Mens athletics', '800 metres – Half marathon', 'Maltese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mattie', 'Sasser', '(age 27)', 'Weightlifting', '–64 kg', 'Marshall Islands / United States', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Karina', 'Alanis', '(age 30)', 'Sprint kayak', 'K–2 1000 m', 'Mexican', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Osmar', 'Olvera', '(age 19)', 'Diving', '3 m springboard', 'Mexican', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Osmar', 'Olvera', '(age 19)', 'Diving', '3 m springboard', 'Mexican', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Carlos', 'Sansores', '(age 26)', 'Taekwondo', '+87 kg', 'Mexican', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Daniela', 'Souza', '(age 24)', 'Taekwondo', '-49 kg', 'Mexican', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Victor', 'Ciobanu', '(age 31)', 'Amateur wrestling', 'Greco-Roman', 'Moldovan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Galbadrakhyn', 'Khishigsaikhan', '(age 33)', 'Long-distance running', 'Marathon', 'Mongolian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Bayartsogtyn', 'Mönkhzayaa', '(age 30)', 'Track and field', 'Marathon', 'Mongolian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tömör-Ochiryn', 'Tulga', '(age 26)', 'Wrestling', 'Freestyle', 'Mongolia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mönkhtöriin', 'Lkhagvagerel', '(age 26)', 'Amateur wrestling', 'Freestyle', 'Mongolia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Dolgorjavyn', 'Otgonjargal', '(age 22)', 'Wrestling', 'Freestyle', 'Mongolia', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Batkhuyagiin', 'Khulan', '(age 24)', 'Wrestling', 'Freestyle', 'Mongolia', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pürevdorjiin', 'Orkhon', '(age 30)', 'Wrestling', 'Freestyle', 'Mongolia', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Noura', 'Ennadi', '(age 25)', 'Athletics', '400m hurdles', 'Morocco', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mathis', 'Soudi', '(age 24)', 'Canoe slalom', 'K1', 'Moroccan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Helalia', 'Johannes', '(age 43)', 'Athletics', 'Notes', 'Namibian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Phillip', 'Seidler', '(age 26)', 'Swimming', 'Open water swimming', 'Namibian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Khalid', 'Choukoud', '(age 38)', 'Athletics', 'Marathon', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Abdi', 'Nageeye', '(age 35)', 'Athletics', 'Time', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sifan', 'Hassan', '(age 31)', 'Athletics', 'Result', 'Dutch', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Maayke', 'Tjin-A-Lim', '(age 26)', 'Track and Field', 'Time', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sven', 'Roosen', '(age 22)', 'Athletics', 'Decathlon', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Martina', 'Wegman', '(age 34)', 'Canoe slalom', 'K1, Extreme K1', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kenzo', 'Simons', '(age 23)', 'Swimming', 'Time', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Arno', 'Kamminga', '(age 28)', 'Swimming', 'Time', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Arno', 'Kamminga', '(age 28)', 'Swimming', 'Time', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nyls', 'Korstanje', '(age 25)', 'Swimming', 'Time', 'Dutch', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tes', 'Schouten', '(age 23)', 'Swimming', 'Time', 'Dutch', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tes', 'Schouten', '(age 23)', 'Swimming', 'Time', 'Dutch', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tori', 'Peeters', '(age 30)', 'Track and Field', 'javelin', 'New Zealand', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Finn', 'Butcher', '(age 29)', 'Canoe slalom', 'K1, Kayak cross', 'New Zealand', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lisa', 'Carrington', '(age 34)', 'Sprint kayak', '1st', 'New Zealand', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lisa', 'Carrington', '(age 34)', 'Sprint kayak', '1st', 'New Zealand', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tayla', 'Ford', '(age 30)', 'Wrestling', 'Womens Wrestling (FW/LF) 58 kg', 'New Zealand', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Godson', 'Oghenebrume', '(age 20)', 'Athletics', 'Sprint', 'Nigerian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Emmanuel', 'Bamidele', '(age 24)', 'Athletics', '400m', 'Nigerian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Samuel', 'Ogazi', '(age 18)', 'Athletics', 'Sprint', 'Nigerian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Edose', 'Ibadin', '(age 31)', 'Athletics', '800 metres', 'Nigerian, American', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ezekiel', 'Nathaniel', '(age 20)', 'Track and Field', '400 metres hurdles', 'Nigerian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ella', 'Onojuvwevwo', '(age 19)', 'Athletics', 'Sprint', 'Nigerian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ayomide', 'Bello', '(age 22)', 'Canoe slalom', 'C-1 & C-2', 'Nigerian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Odunayo', 'Adekuoroye', '(age 30)', 'Wrestling', 'Womens 53 kg', 'Nigerian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Hannah', 'Rueben', '(age 30)', 'Freestyle Wrestling', '-69 kg', 'Nigerian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Dario', 'Ivanovski', '(age 27)', 'Track, long-distance running', '1500 meters', 'North Macedonia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sondre', 'Guttormsen', '(age 24)', 'Track and field', 'Result', 'Norwegian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sander', 'Skotheim', '(age 21)', 'Track and Field', 'decathlon', 'Norwegian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kishmala', 'Talat', '(age 21)', 'Sports shooting', '1st', 'Pakistani', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Cristhian', 'Pacheco', '(age 30)', 'Track and field', 'Place', 'Peruvian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Elreen', 'Ando', '(age 25)', 'Weightlifting', '1st', 'Filipino', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Vanessa', 'Sarno', '(age 20)', 'Weightlifting', '1st', 'Filipino', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Alicja', 'Konieczek', '(age 29)', 'Athletics', 'Notes', 'Polish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Piotr', 'Lisek', '(age 31)', 'Athletics', 'Date', 'Polish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Wojciech', 'Nowicki', '(age 35)', 'Athletics', 'Notes', 'Polish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Paweł', 'Fajdek', '(age 34)', 'Athletics', 'Notes', 'Polish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Anita', 'Włodarczyk', '(age 38)', 'Athletics', '1st', 'Polish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aleksandra', 'Mirosław', '(age 30)', 'Competition climbing', 'Speed', 'Polish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pedro', 'Pichardo', '(age 30)', 'Athletics', 'Measure', 'Portuguese', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Auriol', 'Dongmo', '(age 33)', 'Track and field', 'Result', 'Portuguese', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ayden', 'Owens-Delerme', '(age 23)', 'Track and field', 'Performance', 'Puerto Rican', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Abderrahman', 'Samba', '(age 28)', 'Athletics', 'Time (s)', 'Qatari', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mutaz', 'Essa', '(age 32)', 'Athletics', 'High jump', 'Qatari', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Fares', 'El-Bakh', '(age 25)', 'Weightlifting', '–96 kg', 'Qatari', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Matin', 'Balsini', '(age 23)', 'Swimming', '200 fly', 'Iran', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kasra', 'Mehdipournejad', '(age 31)', 'Taekwondo', 'Heavyweight ( –80 kg)', 'Iranian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Yekta', 'Jamali', '(age 19)', 'Weightlifting', '87 kg', 'Iran', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Alina', 'Rotaru', '(age 30)', 'Athletics', 'Notes', 'Romanian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Bianca', 'Ghelber', '(age 33)', 'Track and field', 'Hammer throw', 'Romanian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Loredana', 'Toma', '(age 29)', 'Weightlifting', '–71 kg', 'Romanian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Alin', 'Alexuc-Ciurariu', '(age 34)', 'Wrestling', 'Greco-Roman', 'Romania', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Angelina', 'Topić', '(age 18)', 'Athletics', 'Performance', 'Serbian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Milica', 'Gardašević', '(age 25)', 'Athletics', 'Notes', 'Serbian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ivana', 'Španović', '(age 34)', 'Track and field', 'Result', 'Serbian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Georgii', 'Tibilov', '(age 39)', 'Wrestling', 'Freestyle', 'Ukraine', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Amita', 'Berthier', '(age 23)', 'Fencing', '1st', 'Singaporean', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Amita', 'Berthier', '(age 23)', 'Fencing', '1st', 'Singaporean', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Viktória', 'Forster', '(age 22)', 'Track and Field', 'Notes', 'Slovak', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Matej', 'Beňuš', '(age 36)', 'Canoe slalom', '2007', 'Slovak', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Jakub', 'Grigar', '(age 27)', 'Canoe slalom', '2013', 'Slovak', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zuzana', 'Paňková', '(age 19)', 'Canoe slalom', '2021', 'Slovak', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Eliška', 'Mintálová', '(age 25)', 'Canoe slalom', '2017', 'Slovak', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Marián', 'Kovačócy', '(age 39)', 'Sports shooting', 'Trap', 'Slovak', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zuzana', 'Rehák-Štefečeková', '(age 40)', 'Shooting', 'Trap', 'Slovak', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Danka', 'Barteková', '(age 39)', 'Shooting', 'Skeet', 'Slovak', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tajmuraz', 'Salkazanov', '(age 28)', 'Amateur wrestling', 'Location', 'Ossetian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Maruša', 'Mišmaš-Zrimšek', '(age 29)', 'Track and field', 'Notes', 'Slovenian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tina', 'Šutej', '(age 35)', 'Athletics', 'Pole vault', 'Slovenian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Akani', 'Simbine', '(age 30)', 'Athletics', 'Time', 'South African', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Luxolo', 'Adams', '(age 27)', 'Athletics', 'Sprint', 'South African', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zakithi', 'Nene', '(age 26)', 'Track and Field', '400 m', 'South African', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lythe', 'Pillay', '(age 21)', 'Athletics', '400 metres', 'South African', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Marione', 'Fourie', '(age 22)', 'Track and Field', 'Notes', 'South African', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pieter', 'Coetze', '(age 20)', 'Swimming', 'Time', 'South African', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pieter', 'Coetze', '(age 20)', 'Swimming', 'Time', 'South African', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tatjana', 'Schoenmaker', '(age 26)', 'Swimming', 'Time', 'South African', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tatjana', 'Schoenmaker', '(age 26)', 'Swimming', 'Time', 'South African', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kaylene', 'Corbett', '(age 24)', 'Swimming', '1st', 'South African', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Erin', 'Gallagher', '(age 25)', 'Swimming', '1st', 'South African', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rebecca', 'Meder', '(age 21)', 'Swimming', 'Time', 'South African', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Aimee', 'Canny', '(age 20)', 'Swimming', 'Time', 'South African', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Keum', 'Ji-hyeon', '(age 24)', 'Shooting', 'Air rifle', 'South Korean', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Hwang', 'Sun-woo', '(age 21)', 'Swimming', 'Time', 'South Korean', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kim', 'Woo-min', '(age 22)', 'Swimming', 'Freestyle relay', 'South Korean', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lee', 'Da-bin', '(age 27)', 'Taekwondo', '73 kg', 'South Korean', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Bak', 'Joo-hyo', '(age 26)', 'Weightlifting', '1st', 'South Korean', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Miquel', 'Travé', '(age 24)', 'Canoe slalom', 'Result', 'Spanish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Miren', 'Lazkano', '(age 26)', 'Canoe slalom', 'C1, K1, C2 mixed', 'Spanish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Carlos', 'Arévalo', '(age 30)', 'Sprint kayak', 'K-4 500 m', 'Spanish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Adrián', 'Vicente', '(age 24)', 'Taekwondo', 'Mens 58 kg', 'Spanish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Andreas', 'Almgren', '(age 28)', 'Running', 'Notes', 'Swedish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Perseus', 'Karlström', '(age 34)', 'Athletics', 'Racewalking', 'Swedish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Armand', 'Duplantis', '(age 24)', 'Athletics', 'Pole vault', 'Swedish American', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Daniel', 'Ståhl', '(age 31)', 'Athletics', 'Notes', 'Swedish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Emilia', 'Nilsson', '(age 21)', 'Diving', '2019', 'Swedish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Björn', 'Seeliger', '(age 24)', 'Swimming', '1st', 'Swedish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sophie', 'Hansson', '(age 25)', 'Swimming', '1st', 'Swedish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Lore', 'Hoffmann', '(age 27)', 'Track and field', 'Time', 'Swiss French', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Man', 'Asaad', '(age 30)', 'Weightlifting', '+109 kg', 'Syrian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Alphonce', 'Simbu', '(age 32)', 'Track and field', 'Marathon', 'Tanzanian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Magdalena', 'Shauri', '(age 28)', 'Long-distance running', 'Marathon', 'Tanzanian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Panipak', 'Wongpattanakit', '(age 26)', 'Taekwondo', '1st', 'Thai', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Marwa', 'Bouzayani', '(age 27)', 'Athletics', 'Time', 'Tunisian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Siwar', 'Bousetta', '(age 24)', 'Amateur wrestling', 'Freestyle', 'Tunisian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mete', 'Gazoz', '(age 24)', 'Archery', '1st', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mete', 'Gazoz', '(age 24)', 'Archery', '1st', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Yasmani', 'Copello', '(age 37)', 'Athletics', '400m hurdles', 'Cuban/Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Salih', 'Korkmaz', '(age 27)', 'Athletics', 'Race walking', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sultan', 'Haydar', '(age 37)', 'Running', 'Time', 'Turkish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Salih', 'Korkmaz', '(age 27)', 'Athletics', 'Race walking', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Ersu', 'Şaşma', '(age 24)', 'Athletics', 'Pole vault', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Deniz', 'Çınar', '(age 39)', 'Sailing', 'Notes', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Alican', 'Kaynar', '(age 35)', 'Sailing', 'Notes', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('İsmail', 'Keleş', '(age 36)', 'Air pistol', 'Notes', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Oğuzhan', 'Tüzün', '(age 41)', 'Shotgun shooting', 'Notes', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Sena', 'Can', '(age 22)', 'Shooting', 'Skeet', 'Turkish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nafia', 'Kuş', '(age 29)', 'Taekwondo, kickboxing', 'Location', 'Turkish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Taha', 'Akgül', '(age 33)', 'Wrestling', 'Location', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Burhan', 'Akbudak', '(age 28)', 'Amateur wrestling', 'Greco-Roman - 82 kg', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rıza', 'Kayaalp', '(age 34)', 'Wrestling', 'Location', 'Turkish', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Evin', 'Demirhan', '(age 28)', 'Womens freestyle wrestling', '50 kg', 'Turkish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zeynep', 'Yetgil', '(age 23)', 'Womens freestyle wrestling', '53 kg', 'Turkish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Buse', 'Tosun', '(age 28)', 'Womens freestyle wrestling', '68 kg / 72 kg', 'Turkish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Yasemin', 'Adar', '(age 32)', 'Womens freestyle wrestling', '1st', 'Turkish', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Oscar', 'Chelimo', '(age 22)', 'Athletics', 'Result', 'Ugandan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Victor', 'Kiplangat', '(age 24)', 'Athletics Mountain running', 'Time', 'Ugandan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Winnie', 'Nanyondo', '(age 30)', 'Athletics', 'Notes', 'Ugandan', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Joy', 'Cheptoyek', '(age 22)', 'Athletics', 'Long distance running', 'Ugandan', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Olena', 'Sobchuk', '(age 28)', 'Athletics', 'Race walking', 'Ukrainian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mariia', 'Sakharuk', '(age 28)', 'Athletics', 'Racewalking', 'Ukrainian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Yaroslava', 'Mahuchikh', '(age 22)', 'Athletics', 'Best', 'Ukrainian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Maryna', 'Bekh-Romanchuk', '(age 28)', 'Athletics', 'Result', 'Ukrainian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Pavlo', 'Korostylov', '(age 26)', 'Shooting', '1st', 'Ukrainian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Olena', 'Kostevych', '(age 39)', 'Shooting', '2004', 'Ukrainian', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Oleksandr', 'Zheltyakov', '(age 18)', 'Swimming', '1st', 'Ukrainian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Parviz', 'Nasibov', '(age 25)', 'Amateur wrestling', 'Greco-Roman', 'Ukraine', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Zhan', 'Beleniuk', '(age 33)', 'Wrestling', 'Location', 'Ukrainian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Conner', 'Mantz', '(age 27)', 'Track and Field, Road running Cross country running', 'Notes', 'American', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Dakotah', 'Lindwurm', '(age 29)', 'long-distance running', 'Notes', 'American', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Fiona', 'OKeeffe', '(age 25)', 'Athletics', 'Time', 'United States', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nevin', 'Harrison', '(age 21)', 'Sprint canoe', 'C-1 200 m', 'American', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nick', 'Itkin', '(age 24)', 'Fencing', 'Position', 'American', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Nick', 'Itkin', '(age 24)', 'Fencing', 'Position', 'American', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Vincent', 'Hancock', '(age 35)', 'Shooting', 'Skeet', 'American', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Rachel', 'Tozier', '(age 32)', 'Shooting', 'Trap', 'American', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Austen', 'Smith', '(age 22)', 'Sport shooter', 'Skeet shooting', 'United States', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Vincent', 'Hancock', '(age 35)', 'Shooting', 'Skeet', 'American', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Wesley', 'Kitts', '(age 34)', 'Weightlifting', '109 kg', 'United States', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Mason', 'Parris', '(age 24)', 'Wrestling', 'Location', 'American', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Kayla', 'Miracle', '(age 28)', 'Wrestling', 'Freestyle', 'American', 'Femme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Gulomjon', 'Abdullaev', '(age 25)', 'Wrestling', 'Freestyle', 'Uzbekistan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Javrail', 'Shapiev', '(age 27)', 'Amateur wrestling', 'Freestyle', 'Russia', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Julio', 'Mayora', '(age 27)', 'Weightlifting', '–73 kg', 'Venezuelan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Betzabeth', 'Argüello', '(age 33)', 'Wrestling', 'Freestyle', 'Venezuelan', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Muzala', 'Samukonga', '(age 21)', 'Track and field', 'Time', 'Zambian', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Tapiwanashe', 'Makarawu', '(age 23)', 'Athletics', 'Sprint', 'Zimbabwe', 'Homme');
INSERT INTO athletes (nom, prenom, age, sport, event, nationalite, sexe) VALUES ('Isaac', 'Mpofu', '(age 35)', 'Track and field', 'Marathon', 'Zimbabwean', 'Homme');
