INSERT INTO pays (nom) VALUES ('Albania');
INSERT INTO pays (nom) VALUES ('Algeria');
INSERT INTO pays (nom) VALUES ('Andorra');
INSERT INTO pays (nom) VALUES ('Angola [A]');
INSERT INTO pays (nom) VALUES ('Antigua and Barbuda');
INSERT INTO pays (nom) VALUES ('Argentina');
INSERT INTO pays (nom) VALUES ('Armenia');
INSERT INTO pays (nom) VALUES ('Aruba');
INSERT INTO pays (nom) VALUES ('Australia');
INSERT INTO pays (nom) VALUES ('Austria');
INSERT INTO pays (nom) VALUES ('Azerbaijan');
INSERT INTO pays (nom) VALUES ('Bahamas');
INSERT INTO pays (nom) VALUES ('Bahrain');
INSERT INTO pays (nom) VALUES ('Barbados');
INSERT INTO pays (nom) VALUES ('Belgium');
INSERT INTO pays (nom) VALUES ('Benin');
INSERT INTO pays (nom) VALUES ('Bermuda');
INSERT INTO pays (nom) VALUES ('Bhutan');
INSERT INTO pays (nom) VALUES ('Bolivia');
INSERT INTO pays (nom) VALUES ('Bosnia and Herzegovina');
INSERT INTO pays (nom) VALUES ('Botswana');
INSERT INTO pays (nom) VALUES ('Brazil');
INSERT INTO pays (nom) VALUES ('British Virgin Islands');
INSERT INTO pays (nom) VALUES ('Bulgaria');
INSERT INTO pays (nom) VALUES ('Burkina Faso');
INSERT INTO pays (nom) VALUES ('Cameroon');
INSERT INTO pays (nom) VALUES ('Canada');
INSERT INTO pays (nom) VALUES ('Cape Verde');
INSERT INTO pays (nom) VALUES ('Cayman Islands');
INSERT INTO pays (nom) VALUES ('Chad');
INSERT INTO pays (nom) VALUES ('Chile');
INSERT INTO pays (nom) VALUES ('China');
INSERT INTO pays (nom) VALUES ('Colombia');
INSERT INTO pays (nom) VALUES ('Costa Rica');
INSERT INTO pays (nom) VALUES ('Croatia');
INSERT INTO pays (nom) VALUES ('Cuba');
INSERT INTO pays (nom) VALUES ('Cyprus');
INSERT INTO pays (nom) VALUES ('Czech Republic');
INSERT INTO pays (nom) VALUES ('Democratic Republic of the Congo');
INSERT INTO pays (nom) VALUES ('Denmark');
INSERT INTO pays (nom) VALUES ('Djibouti');
INSERT INTO pays (nom) VALUES ('Dominica');
INSERT INTO pays (nom) VALUES ('Dominican Republic');
INSERT INTO pays (nom) VALUES ('Ecuador');
INSERT INTO pays (nom) VALUES ('Egypt');
INSERT INTO pays (nom) VALUES ('El Salvador');
INSERT INTO pays (nom) VALUES ('Eritrea');
INSERT INTO pays (nom) VALUES ('Estonia');
INSERT INTO pays (nom) VALUES ('Ethiopia');
INSERT INTO pays (nom) VALUES ('Fiji');
INSERT INTO pays (nom) VALUES ('Finland');
INSERT INTO pays (nom) VALUES ('France (host)');
INSERT INTO pays (nom) VALUES ('Gabon');
INSERT INTO pays (nom) VALUES ('The Gambia');
INSERT INTO pays (nom) VALUES ('Georgia');
INSERT INTO pays (nom) VALUES ('Germany');
INSERT INTO pays (nom) VALUES ('Ghana');
INSERT INTO pays (nom) VALUES ('Great Britain');
INSERT INTO pays (nom) VALUES ('Greece');
INSERT INTO pays (nom) VALUES ('Grenada');
INSERT INTO pays (nom) VALUES ('Guam');
INSERT INTO pays (nom) VALUES ('Guatemala');
INSERT INTO pays (nom) VALUES ('Guinea');
INSERT INTO pays (nom) VALUES ('Guinea-Bissau');
INSERT INTO pays (nom) VALUES ('Hong Kong');
INSERT INTO pays (nom) VALUES ('Honduras');
INSERT INTO pays (nom) VALUES ('Hungary');
INSERT INTO pays (nom) VALUES ('Iceland');
INSERT INTO pays (nom) VALUES ('India');
INSERT INTO pays (nom) VALUES ('Individual Neutral Athletes');
INSERT INTO pays (nom) VALUES ('Indonesia');
INSERT INTO pays (nom) VALUES ('Iran');
INSERT INTO pays (nom) VALUES ('Iraq');
INSERT INTO pays (nom) VALUES ('Ireland');
INSERT INTO pays (nom) VALUES ('Israel');
INSERT INTO pays (nom) VALUES ('Italy');
INSERT INTO pays (nom) VALUES ('Ivory Coast');
INSERT INTO pays (nom) VALUES ('Jamaica');
INSERT INTO pays (nom) VALUES ('Japan');
INSERT INTO pays (nom) VALUES ('Jordan');
INSERT INTO pays (nom) VALUES ('Kazakhstan');
INSERT INTO pays (nom) VALUES ('Kenya');
INSERT INTO pays (nom) VALUES ('Kosovo');
INSERT INTO pays (nom) VALUES ('Kuwait');
INSERT INTO pays (nom) VALUES ('Kyrgyzstan');
INSERT INTO pays (nom) VALUES ('Latvia');
INSERT INTO pays (nom) VALUES ('Lebanon');
INSERT INTO pays (nom) VALUES ('Lesotho');
INSERT INTO pays (nom) VALUES ('Liberia');
INSERT INTO pays (nom) VALUES ('Libya');
INSERT INTO pays (nom) VALUES ('Lithuania');
INSERT INTO pays (nom) VALUES ('Luxembourg');
INSERT INTO pays (nom) VALUES ('Madagascar');
INSERT INTO pays (nom) VALUES ('Malaysia');
INSERT INTO pays (nom) VALUES ('Maldives');
INSERT INTO pays (nom) VALUES ('Mali');
INSERT INTO pays (nom) VALUES ('Malta');
INSERT INTO pays (nom) VALUES ('Marshall Islands');
INSERT INTO pays (nom) VALUES ('Mauritius');
INSERT INTO pays (nom) VALUES ('Mexico');
INSERT INTO pays (nom) VALUES ('Moldova');
INSERT INTO pays (nom) VALUES ('Monaco');
INSERT INTO pays (nom) VALUES ('Mongolia');
INSERT INTO pays (nom) VALUES ('Montenegro');
INSERT INTO pays (nom) VALUES ('Morocco');
INSERT INTO pays (nom) VALUES ('Mozambique');
INSERT INTO pays (nom) VALUES ('Myanmar');
INSERT INTO pays (nom) VALUES ('Namibia');
INSERT INTO pays (nom) VALUES ('Nepal');
INSERT INTO pays (nom) VALUES ('Netherlands');
INSERT INTO pays (nom) VALUES ('New Zealand');
INSERT INTO pays (nom) VALUES ('Nicaragua');
INSERT INTO pays (nom) VALUES ('Niger');
INSERT INTO pays (nom) VALUES ('Nigeria');
INSERT INTO pays (nom) VALUES ('North Korea');
INSERT INTO pays (nom) VALUES ('North Macedonia');
INSERT INTO pays (nom) VALUES ('Norway');
INSERT INTO pays (nom) VALUES ('Pakistan');
INSERT INTO pays (nom) VALUES ('Palestine');
INSERT INTO pays (nom) VALUES ('Panama');
INSERT INTO pays (nom) VALUES ('Papua New Guinea');
INSERT INTO pays (nom) VALUES ('Paraguay');
INSERT INTO pays (nom) VALUES ('Peru');
INSERT INTO pays (nom) VALUES ('Philippines');
INSERT INTO pays (nom) VALUES ('Poland');
INSERT INTO pays (nom) VALUES ('Portugal');
INSERT INTO pays (nom) VALUES ('Puerto Rico');
INSERT INTO pays (nom) VALUES ('Qatar');
INSERT INTO pays (nom) VALUES ('Refugee Olympic Team');
INSERT INTO pays (nom) VALUES ('Romania');
INSERT INTO pays (nom) VALUES ('Rwanda');
INSERT INTO pays (nom) VALUES ('Saint Lucia');
INSERT INTO pays (nom) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO pays (nom) VALUES ('Samoa');
INSERT INTO pays (nom) VALUES ('San Marino');
INSERT INTO pays (nom) VALUES ('Saudi Arabia');
INSERT INTO pays (nom) VALUES ('Senegal');
INSERT INTO pays (nom) VALUES ('Serbia');
INSERT INTO pays (nom) VALUES ('Singapore');
INSERT INTO pays (nom) VALUES ('Slovakia');
INSERT INTO pays (nom) VALUES ('Slovenia');
INSERT INTO pays (nom) VALUES ('South Africa');
INSERT INTO pays (nom) VALUES ('South Korea');
INSERT INTO pays (nom) VALUES ('South Sudan');
INSERT INTO pays (nom) VALUES ('Spain');
INSERT INTO pays (nom) VALUES ('Sri Lanka');
INSERT INTO pays (nom) VALUES ('Sudan');
INSERT INTO pays (nom) VALUES ('Suriname');
INSERT INTO pays (nom) VALUES ('Sweden');
INSERT INTO pays (nom) VALUES ('Switzerland');
INSERT INTO pays (nom) VALUES ('Syria');
INSERT INTO pays (nom) VALUES ('Chinese Taipei');
INSERT INTO pays (nom) VALUES ('Tajikistan');
INSERT INTO pays (nom) VALUES ('Tanzania');
INSERT INTO pays (nom) VALUES ('Thailand');
INSERT INTO pays (nom) VALUES ('Togo');
INSERT INTO pays (nom) VALUES ('Trinidad and Tobago');
INSERT INTO pays (nom) VALUES ('Tunisia');
INSERT INTO pays (nom) VALUES ('Turkey');
INSERT INTO pays (nom) VALUES ('Turkmenistan');
INSERT INTO pays (nom) VALUES ('Uganda');
INSERT INTO pays (nom) VALUES ('Ukraine');
INSERT INTO pays (nom) VALUES ('United Arab Emirates');
INSERT INTO pays (nom) VALUES ('United States');
INSERT INTO pays (nom) VALUES ('Uruguay');
INSERT INTO pays (nom) VALUES ('Uzbekistan');
INSERT INTO pays (nom) VALUES ('Vanuatu');
INSERT INTO pays (nom) VALUES ('Venezuela');
INSERT INTO pays (nom) VALUES ('Vietnam');
INSERT INTO pays (nom) VALUES ('Virgin Islands');
INSERT INTO pays (nom) VALUES ('Zambia');
INSERT INTO pays (nom) VALUES ('Zimbabwe');
