INSERT INTO discipline (nom) VALUES ('Aquatics');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Artistic swimming');
INSERT INTO discipline (nom) VALUES ('Diving');
INSERT INTO discipline (nom) VALUES ('Marathon swimming');
INSERT INTO discipline (nom) VALUES ('Swimming');
INSERT INTO discipline (nom) VALUES ('Water polo');
INSERT INTO discipline (nom) VALUES ('Archery');
INSERT INTO discipline (nom) VALUES ('Athletics');
INSERT INTO discipline (nom) VALUES ('Badminton');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('Basketball');
INSERT INTO discipline (nom) VALUES ('3×3 basketball');
INSERT INTO discipline (nom) VALUES ('Boxing');
INSERT INTO discipline (nom) VALUES ('Breaking');
INSERT INTO discipline (nom) VALUES ('Canoeing');
INSERT INTO discipline (nom) VALUES ('Slalom');
INSERT INTO discipline (nom) VALUES ('Sprint');
INSERT INTO discipline (nom) VALUES ('Cycling');
INSERT INTO discipline (nom) VALUES ('BMX freestyle');
INSERT INTO discipline (nom) VALUES ('BMX racing');
INSERT INTO discipline (nom) VALUES ('Mountain biking');
INSERT INTO discipline (nom) VALUES ('Road');
INSERT INTO discipline (nom) VALUES ('Track');
INSERT INTO discipline (nom) VALUES ('Equestrian');
INSERT INTO discipline (nom) VALUES ('Dressage');
INSERT INTO discipline (nom) VALUES ('Eventing');
INSERT INTO discipline (nom) VALUES ('Jumping');
INSERT INTO discipline (nom) VALUES ('Fencing');
INSERT INTO discipline (nom) VALUES ('Field hockey');
INSERT INTO discipline (nom) VALUES ('Football');
INSERT INTO discipline (nom) VALUES ('Golf');
INSERT INTO discipline (nom) VALUES ('Gymnastics');
INSERT INTO discipline (nom) VALUES ('Artistic');
INSERT INTO discipline (nom) VALUES ('Rhythmic');
INSERT INTO discipline (nom) VALUES ('Trampoline');
INSERT INTO discipline (nom) VALUES ('Handball');
INSERT INTO discipline (nom) VALUES ('Judo');
INSERT INTO discipline (nom) VALUES ('Modern pentathlon');
INSERT INTO discipline (nom) VALUES ('Rowing');
INSERT INTO discipline (nom) VALUES ('Rugby sevens');
INSERT INTO discipline (nom) VALUES ('Sailing');
INSERT INTO discipline (nom) VALUES ('Shooting');
INSERT INTO discipline (nom) VALUES ('Skateboarding');
INSERT INTO discipline (nom) VALUES ('Sport climbing');
INSERT INTO discipline (nom) VALUES ('Surfing');
INSERT INTO discipline (nom) VALUES ('Table tennis');
INSERT INTO discipline (nom) VALUES ('Taekwondo');
INSERT INTO discipline (nom) VALUES ('Tennis');
INSERT INTO discipline (nom) VALUES ('Triathlon');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Volleyball');
INSERT INTO discipline (nom) VALUES ('Beach volleyball');
INSERT INTO discipline (nom) VALUES ('Weightlifting');
INSERT INTO discipline (nom) VALUES ('Wrestling');
INSERT INTO discipline (nom) VALUES ('Freestyle');
INSERT INTO discipline (nom) VALUES ('Greco-Roman');
