INSERT INTO evenement (nom, discipline_id) VALUES ('Artistic swimming Duet', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Artistic swimming Team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Artistic swimming Duet', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Artistic swimming Team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Diving 3 m springboard', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Diving 10 m platform', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Diving Synchronized 3 m springboard', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Diving Synchronized 10 m platform', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Diving 3 m springboard', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Diving 10 m platform', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Diving Synchronized 3 m springboard', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Diving Synchronized 10 m platform', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 50 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 100 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 400 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 800 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 1500 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 100 m backstroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m backstroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 100 m breaststroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m breaststroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 100 m butterfly', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m butterfly', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m individual medley', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 400 m individual medley', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 4 × 100 m freestyle relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 4 × 200 m freestyle relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 4 × 100 m medley relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 10 km open water', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 50 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 100 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 400 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 800 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 1500 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 100 m backstroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m backstroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 100 m breaststroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m breaststroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 100 m butterfly', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m butterfly', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 200 m individual medley', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 400 m individual medley', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 4 × 100 m freestyle relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 4 × 200 m freestyle relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 4 × 100 m medley relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 10 km open water', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Marathon swimming 4 × 100 m medley relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 50 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 100 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 400 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 800 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 1500 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 100 m backstroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m backstroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 100 m breaststroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m breaststroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 100 m butterfly', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m butterfly', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m individual medley', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 400 m individual medley', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 4 × 100 m freestyle relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 4 × 200 m freestyle relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 4 × 100 m medley relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 10 km open water', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 50 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 100 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 400 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 800 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 1500 m freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 100 m backstroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m backstroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 100 m breaststroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m breaststroke', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 100 m butterfly', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m butterfly', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 200 m individual medley', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 400 m individual medley', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 4 × 100 m freestyle relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 4 × 200 m freestyle relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 4 × 100 m medley relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 10 km open water', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Swimming 4 × 100 m medley relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Water polo Men s tournament', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Water polo Women s tournament', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Archery Men s individual', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Archery Men s team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Archery Women s individual', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Archery Women s team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Archery Mixed team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 100 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 200 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 400 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 800 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 1500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 5000 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 10,000 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 110 metres hurdles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 400 metres hurdles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 3000 metres steeplechase', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 4 × 100 metres relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 4 × 400 metres relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Marathon', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 20 kilometres walk', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics High jump', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Pole vault', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Long jump', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Triple jump', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Shot put', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Discus throw', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Hammer throw', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Javelin throw', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Decathlon', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 100 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 200 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 400 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 800 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 1500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 5000 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 10,000 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 100 metres hurdles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 400 metres hurdles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 3000 metres steeplechase', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 4 × 100 metres relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 4 × 400 metres relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Marathon', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 20 kilometres walk', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics High jump', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Pole vault', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Long jump', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Triple jump', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Shot put', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Discus throw', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Hammer throw', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Javelin throw', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Heptathlon', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics 4 × 400 metres relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Athletics Marathon walk relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Badminton Men s singles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Badminton Men s doubles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Badminton ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Badminton Women s singles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Badminton Women s doubles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Badminton ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Badminton Mixed doubles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Basketball Men', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Basketball Women', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Basketball Men 3x3', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Basketball Women 3x3', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 51 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 57 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 63.5 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 71 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 80 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 92 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing +92 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 50 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 54 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 57 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 60 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 66 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing 75 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Boxing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Breaking B-Boys', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Breaking B-Girls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing Men s C-1', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing Men s K-1', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing Men s Kayak cross', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing Women s C-1', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing Women s K-1', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing Women s Kayak cross', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing C-1 1000 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing C-2 500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing K-1 1000 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing K-2 500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing K-4 500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing C-1 200 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing C-2 500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing K-1 500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing K-2 500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Canoeing K-4 500 metres', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Men s road race', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Men s time trial', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Women s road race', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Women s time trial', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Sprint', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Team sprint', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Keirin', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Madison', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Omnium', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Team pursuit', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Sprint', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Team sprint', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Keirin', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Madison', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Omnium', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Team pursuit', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Men s cross-country', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Women s cross-country', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Men s race', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Men s freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Women s race', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Cycling Women s freestyle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Equestrian Individual dressage', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Equestrian Team dressage', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Equestrian ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Equestrian Individual eventing', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Equestrian Team eventing', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Equestrian ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Equestrian Individual jumping', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Equestrian Team jumping', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Individual épée', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Team épée', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Individual foil', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Team foil', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Individual sabre', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Team sabre', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Individual épée', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Team épée', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Individual foil', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Team foil', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Individual sabre', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Fencing Team sabre', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Field hockey Men', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Field hockey Women', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Football Men', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Football Women', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Golf Men s individual', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Golf Women s individual', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Team all-around', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Individual all-around', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Floor exercise', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Pommel horse', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Rings', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Vault', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Parallel bars', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Horizontal bar', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Team all-around', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Individual all-around', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Vault', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Uneven bars', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Balance beam', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Floor exercise', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Group all-around', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Individual all-around', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Men s individual', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Gymnastics Women s individual', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Handball Men', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Handball Women', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Extra-lightweight (60 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Half-lightweight (66 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Lightweight (73 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Half-middleweight (81 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Middleweight (90 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Half-heavyweight (100 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Heavyweight (+100 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Extra-lightweight (48 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Half-lightweight (52 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Lightweight (57 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Half-middleweight (63 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Middleweight (70 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Half-heavyweight (78 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Heavyweight (+78 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo Mixed team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Judo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Modern pentathlon Men s', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Modern pentathlon Women s', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Single sculls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Double sculls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Quadruple sculls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Coxless pair', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Coxless four', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Coxed eight', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Lightweight double sculls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Single sculls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Double sculls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Quadruple sculls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Coxless pair', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Coxless four', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Coxed eight', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rowing Lightweight double sculls', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rugby sevens Men s tournament', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Rugby sevens Women s tournament', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing IQFoil', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing Formula Kite', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing ILCA 7', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing 49er', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing IQFoil', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing Formula Kite', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing ILCA 6', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing 49erFX', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing 470', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sailing Nacra 17', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 10 metre air pistol', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 25 metre rapid fire pistol', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 10 metre air rifle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 50 metre rifle three positions', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting Skeet', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting Trap', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 10 metre air pistol', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 25 metre pistol', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 10 metre air rifle', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 50 metre rifle three positions', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting Skeet', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting Trap', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 10 metre air pistol team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting 10 metre air rifle team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Shooting Skeet team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Skateboarding Men s park', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Skateboarding Women s park', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Skateboarding ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Skateboarding Men s street', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Skateboarding Women s street', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sport climbing Men s combined', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sport climbing Women s combined', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sport climbing Men s speed', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Sport climbing Women s speed', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Surfing Men s shortboard', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Surfing Women s shortboard', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Table tennis Men s singles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Table tennis Men s team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Table tennis ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Table tennis Women s singles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Table tennis Women s team', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Table tennis ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Table tennis Mixed doubles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo Flyweight (58 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo Featherweight (68 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo Welterweight (80 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo Heavyweight (+80 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo Flyweight (49 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo Featherweight (57 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo Welterweight (67 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo Heavyweight (+67 kg)', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Taekwondo ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Tennis Men s singles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Tennis Men s doubles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Tennis ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Tennis Women s singles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Tennis Women s doubles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Tennis ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Tennis Mixed doubles', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Triathlon Men s individual', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Triathlon Women s individual', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Triathlon Mixed relay', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Volleyball Men s beach', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Volleyball Women s beach', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Volleyball Men s tournament', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Volleyball Women s tournament', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting 61 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting 73 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting 89 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting 102 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting +102 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting 49 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting 59 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting 71 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting 81 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Weightlifting +81 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 57 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 65 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 74 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 86 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 97 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 125 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 60 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 67 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 77 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 87 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 97 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 130 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 50 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 53 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 57 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 62 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 68 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling 76 kg', NULL);
INSERT INTO evenement (nom, discipline_id) VALUES ('Wrestling ', NULL);